apiVersion: apps/v1
kind: Deployment
metadata:
  name: mateapp-deployment
  namespace: mateapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: mateapp
  template:
    metadata:
      labels:
        app: mateapp
    spec:
      containers:
      - name: mateapp-container
        image: dimonalek/todoapp:3.0.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80